version: '3'
services:

  gate:
    build: ./artifacts/gate-simulator/
    image: gate:diploma
    ports:
      - '9999:9999'

  my:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'app'
      MYSQL_USER: 'app'
      MYSQL_PASSWORD: 'pass'
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
    security_opt:
      - seccomp=unconfined
        
  pg:
    image: postgres:12.8-alpine3.14
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass
   
  adminer:
    image: adminer
    restart: always
    depends_on:
      - my
      - pg
    ports:
      - '8000:8080'

