version: '3.9'

services:

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'app'
      MYSQL_USER: 'app'
      MYSQL_PASSWORD: 'pass'
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
    security_opt:
      - seccomp=unconfined

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - '8000:8080'
